AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SpringBoot on AWS Lambda Study

Globals:
  Function:
    Timeout: 60
    Environment:
      Variables:
        DATABASE_ENDPOINT: !Ref DatabaseEndpoint

Parameters:
  DatabaseEndpoint:
    Description: ysb-test-database.cpgkx9kinjev.ap-northeast-2.rds.amazonaws.com
    #데이터베이스 주소
    Type: String

Resources:
  SpringLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.ysb.jwgio.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: .
      MemorySize: 2048
      Timeout: 60
      AutoPublishAlias: latest
      SnapStart:
        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        SpringLambda:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY


